#!/bin/bash
chown -R ${APP_USER}:${APP_GROUP} ${APP_HOME} /etc/elasticsearch /etc/sysconfig/elasticsearch /var/log/elasticsearch /var/lib/elasticsearch
cd ${APP_HOME}
gosu ${APP_USER}:${APP_GROUP} /usr/share/elasticsearch/bin/elasticsearch \
    -p ${PID_DIR}/elasticsearch.pid \
    $@ 

